# Generated by Django 2.0.6 on 2018-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modifylist', '0004_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='new', max_length=100),
        ),
    ]
